# Generated by Django 2.2.7 on 2019-11-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0002_commit_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='author_avatar',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='commit',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
