# Generated by Django 2.2.7 on 2019-11-26 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_auto_20191124_1640'),
        ('commits', '0003_auto_20191124_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='repo',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='repositories.Repository'),
        ),
    ]
