# Generated by Django 2.2.7 on 2019-11-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='repository',
            name='forks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='repository',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
