# Generated by Django 2.2.7 on 2019-11-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_auto_20191124_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrepository',
            old_name='repo_id',
            new_name='repo',
        ),
    ]
