# Generated by Django 2.2.7 on 2019-11-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_auto_20191124_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='forks',
            new_name='fork',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='stars',
            new_name='star',
        ),
    ]
