# Generated by Django 2.2.7 on 2019-12-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_auto_20191124_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='hook_id',
            field=models.IntegerField(default=0),
        ),
    ]
